apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashicorpvault
  namespace: default
spec:
  selector:
    matchLabels:
      app: hashicorpvault
  replicas: 1 # we always run a single replica of the operator to avoid duplicate handling of events
  strategy:
    type: Recreate # during an upgrade the operator will shut down before the new version comes up to prevent two instances running at the same time
  template:
    metadata:
      labels:
        app: hashicorpvault
    spec:
      containers:
        - name: hashicorpvault
          image: docker.io/vault:latest
          imagePullPolicy: Always
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: myroottoken
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: 0.0.0.0:8200
          ports:
            - containerPort: 8200
          readinessProbe:
            httpGet:
              path: /ui # when this returns 200 the operator is considered up and running
              port: 8200
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ui
              port: 8200
            initialDelaySeconds: 15
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  creationTimestamp: null
  labels:
    app: hashicorpvault
  name: hashicorpvault
spec:
  ports:
    - name: "8200"
      port: 8200
      protocol: TCP
      targetPort: 8200
  selector:
    app: hashicorpvault
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hashicorpvault
                port:
                  number: 8200