apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  variable_encrypted: "<encrypted>Lz3vP6mVDzUhOX6wZT+XGHmyvl6l0uQU+PJo+vM2+6dM6f3MWjkKR69ih/uPtzoT8NRoHWrhFmjX5WwFIYpCfEppA9o/6tlus4Vjr3gtPJER0S3Vb6Kt1+/WDf+rPPbd6WmC5O3R9pEd1JGrMcBhAUQfQb6r9bXzT1qRjqH3FcAmnVGa3FHhFYHz1JvOvaiyO0zFOIEFuq7XkguBDh8ALmdA5INwJLGxiIYTFPGQx6w0Wg/Hcpe0TDShR41Qoqr8j0v0VoLcz6xHX+6GTGdvC/V/7+rKTT4prp916URweQc7RDqwMn43Hu9adPA8dETvWl0dt0n+N2wg2S8j9R1av5IWFevBt9g00kYEzt3Kv9tPAtpwQZbJrJpRizh5lkGLFdgKd1/VCD7CY5hD3hvQ8vfb/gQ75N5gYbmsK7qCZlAkuvPFclv7wsieo/tS4BdQpQoFUYSDW+WNMdFNQDj7NsT0VmNRjSgpA8Sc5fo8JZkG3qW/egWyvatLB0hyq3i76cS+5aoMKSoC8fpmcD6NyEM48k0uHvUcfKZFXfW441rKWY5w8wOf87k6kms7fCuo1JFEiRGreurENyuQZjf0iX9NgIddbIL1HK9WumUlHffX3AKSgoTx3/3xxPdGkcdrsPOaMP4mnbOrsdqXPiL22AAKNLETTpTG3KPbTPOtJ7Y="
  variable_unencrypted: "Hallo"