apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultsecrets.commons.init.de
spec:
  group: commons.init.de
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                passwords:
                  type: array
                  items:
                    type: string
#              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                secretCreated:
                  type: boolean
                dateSecretCreated:
                  type: string
                dateSecretChanged:
                  type: string
#              x-kubernetes-preserve-unknown-fields: true
#              private boolean secretCreated;
              #    private String dateSecretCreated;
              #    private String dateSecretChanged;
  names:
    kind: VaultSecret
    plural: vaultsecrets
    singular: vaultsecret
    shortNames:
      - vs
  scope: Namespaced